import { clasificarTodosLosMedidores } from "./clasificacionMedidores";

export const medidores = {
  agua: [
    {
      instrumento: "Contadores de Agua de Chorro Único",
      presión: {min:0, max:16},
      flujo: {min:0.03, max:3},
      precision_estimada: 3,
      presupuesto: 100,
      soporte: 1,
      disponibilidad: 2,
      certificacion: 1,
      instalacion: 1,
    },
    {
      instrumento: "Contadores de Agua de Chorro múltiple",
      presión: {min:0, max:16},
      flujo: {min:0.03, max:3},
      precision_estimada: 1,
      presupuesto: 250,
      soporte: 2,
      disponibilidad: 2,
      certificacion: 1,
      instalacion: 2,
    },
    {
      instrumento: "Contador de agua tangencial",
      presión: {min:0, max:16},
      flujo: {min:1.2, max:30},
      precision_estimada: 1,
      presupuesto: 300,
      soporte: 2,
      disponibilidad: 3,
      certificacion: 1,
      instalacion: 3,
    },
    {
      instrumento: "Contador de Agua Woltmann",
      presión: {min:0, max:16},
      flujo: {min:0.25, max:78.75},
      precision_estimada: 1,
      presupuesto: 160,
      soporte: 2,
      disponibilidad: 2,
      certificacion: 1,
      instalacion: 1,
    },
    {
      instrumento: "Contador de Agua De Pistón Rotativo y Disco Oscilante",
      presión: {min:0.3, max:16},
      flujo: {min:0.0064, max:2},
      precision_estimada: 0.5,
      presupuesto: 300,
      soporte: 3,
      disponibilidad: 2,
      certificacion: 3,
      instalacion: 2,
    },
    {
      instrumento: "Contador de Agua Electromagnético",
      presión: {min:0, max:10.3421},
      flujo:  {min:3, max:60},
      precision_estimada: 2,
      presupuesto: 300,
      soporte: 3,
      disponibilidad: 3,
      certificacion: 2,
      instalacion: 2,
    },
    {
      instrumento: "Contador de Agua ultrasónico",
      presión: {min:0, max:16},
      flujo: {min:0.05, max:31.5},
      precision_estimada: 1,
      presupuesto: 250,
      soporte: 2,
      disponibilidad: 3,
      certificacion: 2,
      instalacion: 3,
    },
    {
      instrumento: "Contador de Agua de desplazamiento Positivo y medidores de Velocidad",
      presión: {min:0, max:19.5},
      flujo: {min:10, max:97},
      precision_estimada: 0.5,
      presupuesto: 350,
      soporte: 3,
      disponibilidad: 2,
      certificacion: 3,
      instalacion: 3,
    },
    {
      instrumento: "Contador de agua de pistón oscilante y discos Nutantes",
      presión: {min:0, max:67},
      flujo: {min:0.09, max:0.9},
      precision_estimada: 1,
      presupuesto: 250,
      soporte: 3,
      disponibilidad: 2,
      certificacion: 2,
      instalacion: 2,
    },
  ],
  electricidad: [
    {
      instrumento: "Medidor monofásico",
      voltaje: 120,
      amperaje: {min:5, max:100},
      precision_estimada: 3,
      presupuesto: 50,
      soporte: 2,
      disponibilidad: 3,
      certificacion: 1,
      instalacion: 2,
    },
    {
      instrumento: "Medidor bifásico",
      voltaje: {min:120, max:208},
      amperaje: {min:5, max:100},
      precision_estimada: 0.5,
      presupuesto: 300,
      soporte: 3,
      disponibilidad: 3,
      certificacion: 3,
      instalacion: 2,
    },
    {
      instrumento: "Medidor trifásico",
      voltaje: {min:120, max:208},
      amperaje: {min:5, max:100},
      precision_estimada: 1,
      presupuesto: 180,
      soporte: 2,
      disponibilidad: 3,
      certificacion: 3,
      instalacion: 2,
    },
    {
      instrumento: "Medidor trifásico 3x",
      voltaje: {min:110, max:480},
      amperaje: {min:10, max:150},
      precision_estimada: 1.5,
      presupuesto: 300,
      soporte: 3,
      disponibilidad: 1,
      certificacion: 3,
      instalacion: 2,
    },
    {
      instrumento: "Medidor de conexión semidirecta e indirecta",
      voltaje: {min:58, max:480},
      amperaje: {min:5, max:10},
      precision_estimada: 1,
      presupuesto: 340,
      soporte: 3,
      disponibilidad: 1,
      certificacion: 1,
      instalacion: 3,
    },
  ],
  gas: [
    {
      instrumento: "Contador para gas tipo diafragma",
      presión: {min:0, max:0.5},
      flujo: {min:0.016, max:2.5},
      precision_estimada: 0.5,
      presupuesto: 390,
      soporte: 3,
      disponibilidad: 3,
      certificacion: 3,
      instalacion: 2,
    },
    {
      instrumento: "Contador de gas ultrasónico",
      presión: {min:0, max:153},
      flujo: {min:7, max:610},
      precision_estimada: 0.2,
      presupuesto: 400,
      soporte: 3,
      disponibilidad: 2,
      certificacion: 3,
      instalacion: 3,
    },
    {
      instrumento: "Contador de turbina",
      presión: {min: 16, max: 20},
      flujo: {min: 2, max: 2500},
      precision_estimada: 0.5,
      presupuesto: 340,
      soporte: 3,
      disponibilidad: 3,
      certificacion: 3,
      instalacion: 3,
    },
    {
      instrumento: "Contador de orificio",
      presión: {min: 1.5, max: 12},
      flujo: 4,
      precision_estimada: 2.5,
      presupuesto: 160,
      soporte: 2,
      disponibilidad: 3,
      certificacion: 3,
      instalacion: 2,
    },
    {
      instrumento: "Contador de coriolis",
      presión: {min: 0, max: 16},
      flujo: {min: 0.07, max: 3},
      precision_estimada: 0.2,
      presupuesto: 380,
      soporte: 2,
      disponibilidad: 2,
      certificacion: 3,
      instalacion: 2,
    },
    {
      instrumento: "Contador de flujo másico",
      presión: {min: 0.35, max: 103.4},
      flujo: {min: 0, max: 6},
      precision_estimada: 3,
      presupuesto: 210,
      soporte: 3,
      disponibilidad: 3,
      certificacion: 3,
      instalacion: 2,
    },
    {
      instrumento: "Contador rotativo",
      presión: {min: 0, max: 20},
      flujo: {min: 0.25, max: 25},
      precision_estimada: 0.5,
      presupuesto: 340,
      soporte: 3,
      disponibilidad: 2,
      certificacion: 2,
      instalacion: 3,
    },
    /* { Aqui es donde debe ir la información de cada medidor
      instrumento: "Contador rotativo",
      precision_estimada: 0.5,
      presupuesto: 340,
      soporte: 3,
      disponibilidad: 2,
      certificacion: 2,
      instalacion: 3,
    }, */
  ],
};
export const obtenerMedidoresConClasificacion = () => {
  const medidoresCopiados = JSON.parse(JSON.stringify(medidores));
  clasificarTodosLosMedidores(medidoresCopiados);
  return medidoresCopiados;
};
